### ISSUE TITLE
TIMIT datasource

### ISSUE THREAD

**Issue by lemonade117** [atulkum/neural_sequence_transduction#1]
May I get your datasource? I've found a version stripped-down, and the folder format has also been shuffled, it's hard for me to run your code, please help.

**Comment by lemonade117** [comment]
I wonder where is your h5py file which has two keys 'mfcc' and 'mfcc', I just want to learn to preprocess TIMIT datasource as a torch dataset, please help me.

**Comment by atulkum** [comment]
You can see the main method in this file. If you pass cache=False it will create the h5py files. https://github.com/atulkum/neural_sequence_transduction/blob/master/data_processing/timit.py. I shared my TIMIT dataset here https://drive.google.com/file/d/19ZCnUGWx7ygRYsv6V0rA664NxfLYG6he/view?usp=sharing

**Comment by lemonade117** [comment]
> You can see the main method in this file. If you pass cache=False it will create the h5py files. https://github.com/atulkum/neural_sequence_transduction/blob/master/data_processing/timit.py. I shared my TIMIT dataset here https://drive.google.com/file/d/19ZCnUGWx7ygRYsv6V0rA664NxfLYG6he/view?usp=sharing

thank you so much : )
